language: bash
language: r
sudo: required

install:
  - docker pull dapperstats/accessor
  - docker run --name acc -t dapperstats/accessor
  - docker cp acc:/data .
  - docker cp acc:/scripts .

script:
  - ls data
  - ls scripts
  - docker exec -i acc bash -c "cd acc && Rscript scripts/r_script.R"

after_success:
  - test $TRAVIS_EVENT_TYPE = "cron" &&
    bash scripts/update_github_data.bash 