language: bash
sudo: required

install:
#  - docker pull dapperstats/accessor
  - docker pull rocker/verse

script:
#  - docker run --name acc --restart=always -t dapperstats/accessor
  - docker run --name salv --restart=always -t rocker/verse

#  - docker cp acc:/data .
#  - docker cp acc:/data salv:/
  - docker cp site salv:/  
  - docker cp scripts salv:/ # move into Dockerfile
#  - docker exec -i salv mkdir files # move into Dockerfile
  - docker exec -i salv bash -c "Rscript scripts/salvage_script.R"

  - docker cp salv:/site .

after_success:
  - test $TRAVIS_EVENT_TYPE = "cron" &&
    bash scripts/update_github.bash 