language: bash
sudo: required

install:
  - docker pull dapperstats/salvage_nonint
  - docker run --name salvage_container -t dapperstats/salvage_nonint
  - docker cp salvage_container:/data ./data

script:
  - ls data

after_success:
  - test $TRAVIS_EVENT_TYPE = "pull_request" &&
    bash scripts/update_github_data.bash

