language: bash
sudo: required

install:
  - docker pull dapperstats/accessor
  - docker pull dapperstats/salvage

script:
  - docker run --name acc --restart=always -it dapperstats/accessor
  - docker run --name salv --restart=always -itd dapperstats/salvage

  - docker cp acc:/data .
  - docker cp data salv:/
  - docker cp acc:/scripts .
  - docker cp scripts salv:/
  - docker cp site salv:/

  - travis_wait 50 docker exec -i salv R -e "source('scripts/salvage_script.R')"

  - docker cp salv:/site .
  - docker cp salv:/data .
  - ls site

after_success:
  - test $TRAVIS_EVENT_TYPE = "cron" &&
    bash scripts/update_github.bash 