language: bash
sudo: required

before_install:
  - docker pull dapperstats/salvage_nonint
  - docker run --name salvage_container -t dapperstats/salvage_nonint
  - docker cp salvage_container:/data ./data
  - ls data

after_success:
  if: type = pull_request
    - bash scripts/update_github_data.bash
    

