language: bash
sudo: required

install:
  - docker pull dapperstats/salvage_nonint
  - docker run --name salvage_container -t dapperstats/salvage_nonint
  - docker cp salvage_container:/data .

script:
  - ls data
  - echo `date -I | head -c 10` > data/data_date.txt
  - cat data/data_date.txt
  - wget ftp://ftp.wildlife.ca.gov/salvage/Salvage_data_FTP.accdb -o lol.accdb
  - ls data

after_success:
  - test $TRAVIS_EVENT_TYPE = "cron" &&
    bash scripts/update_github_data.bash

