language: bash
sudo: required

install:
  - docker pull dapperstats/accessor

script:
  - docker run --name acc --restart=always -t dapperstats/accessor
  - docker cp scripts acc:/
  - docker exec -i acc mkdir files
  - docker exec -i acc bash -c "Rscript scripts/salvage_script.R"
  - docker cp acc:/data .
  - docker cp acc:/files ./site/static/files

after_success:
  - test $TRAVIS_EVENT_TYPE = "cron" &&
    bash scripts/update_github_data.bash 