language: bash
sudo: required

stages:
  - name: after_success
    # require the branch name to be master (note for PRs this is the base branch name)
    if: type = pull_resquest

before_install:
  - docker pull dapperstats/salvage_nonint
  - docker run --name salvage_container -t dapperstats/salvage_nonint
  - docker cp salvage_container:/data ./data
  - ls data

after_success:
  - bash scripts/update_github_data.bash
    

