language: bash
sudo: required

install:
  - docker pull dapperstats/accessor
  - docker pull dapperstats/salvage

script:
  - docker run --name acc --restart=always -t dapperstats/accessor
  - docker run --name salv --restart=always -dit dapperstats/salvage

  - docker cp acc:/data .
  - docker cp data salv:/
  - docker cp acc:/scripts .
  - docker cp scripts salv:/
  - docker cp site salv:/

  - docker exec -i salv R -e "source('scripts/salvage_script.R')"

  - docker cp salv:/site .
  - ls site

after_success:
  #- test $TRAVIS_EVENT_TYPE = "cron" &&
  -  bash scripts/update_github.bash 