languageCode = "en-us"
title = "salvage.fish"
theme = "crab"
baseurl = "https://salvage.fish/"
name = "Salvage"
license = "MIT"
licenselink = "https://github.com/dapperstats/salvage/blob/master/LICENSE"
homepage = "https://github.com/dapperstats/salvage"
tags = ["fish", "salvage", "California Delta"]
features = ["responsive", "404", "blog", "tags"]

[author]
name = "Juniper L. Simonis"
homepage = "https://www.dapperstats.com"




[params]
description = "Data from the California Delta fish salvage facilities"
logoimage = "hex.png"


# mathjax = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
## Uncomment if you want mathjax enabled. The above cdn source is taken from https://gohugo.io/content-management/formats/#mathjax-with-hugo   



[permalinks]
blog  = "/blog/:year/:month/:title/"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "Home"
url = "/"


[[menu.main]]
weight = 2
name = "Contact"
url = "/contact/"



