title = "salvage.fish"
theme = "hugo-academic"
baseurl = "https://salvage.fish/"
name = "Salvage"
license = "MIT"
licenselink = "https://github.com/dapperstats/salvage/blob/master/LICENSE"
homepage = "https://github.com/dapperstats/salvage"

enableGitInfo = false
defaultContentLanguage = "en"
hasCJKLanguage = false  
defaultContentLanguageInSubdir = false
removePathAccents = true
paginate = 10
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  
    hrefTargetBlank = false
  [markup.highlight]
    codeFences = false  
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  

[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"
