name = "Crab"
license = "MIT"
licenselink = "https://github.com/thomasheller/crab/blob/master/LICENSE.md"
description = "A clean Hugo theme for websites"
homepage = "https://github.com/thomasheller/crab"
tags = ["clean"]
features = ["responsive", "404", "blog", "tags"]
min_version = 0.18

[author]
name = "Thomas Heller"
homepage = "https://github.com/thomasheller"
