# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.


[[main]]
  name = "Home"
  url = "#home"
  weight = 10


[[main]]
  name = "Source Code"
  url = "https://www.github.com/dapperstats/salvage"
  weight = 20


