#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.


[[main]]
  name = "Home"
  url = "#home"
  weight = 10

[[main]]
  name = "Salvage Summary"
  url = "/summary"
  weight = 30

[[main]]
  name = "Methods"
  url = "/methods"
  weight = 40
  identifier = "methods"

[[main]]
  name = "Overview"
  url = "/methods"
  weight = 41
  parent = "methods"
  identifier = "methods_overview"

[[main]]
  name = "Data Access"
  url = "/data_access"
  weight = 42
  parent = "methods"
  identifier = "data_access"

[[main]]
  name = "Source Code"
  url = "https://www.github.com/dapperstats/salvage"
  weight = 60


