theme = "minimal"
day_night = true
font = ""
font_size = "L"

site_type = "Project"
org_name = "Fish Salvage Tools"
description = ""

highlight = true
highlight_languages = ["r"] 
highlight_style = "github"  

math = true
diagram = true
privacy_pack = false

email = ""
phone = ""

address = {street = "17500 Byron Hwy", city = "Discovery Bay", region = "CA", postcode = "94505", country = "United States", country_code = "US"}
coordinates = {latitude = "37.826290", longitude = "-121.595066"}

directions = ""
office_hours = []
appointment_url = ""
contact_links = []

sharing_image = ""
twitter = ""
sharing = false

date_format = "2006-01-02"
time_format = "3:04 PM"
address_format = "en-us"

main_menu = {align = "l", show_logo = true}
reading_time = false
section_pager = false
docs_section_pager = true  

link_authors = true
plugins_js  = []

[avatar]
  gravatar = false
  shape = "circle"

[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  de = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  fr-fr = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}

[publications]
  date_format = "January 2006"
  citation_style = "apa"

[projects]
  post_view = 0
  publication_view = 0
  talk_view = 0

[comments]
  engine = 0
  commentable = {page = true, post = true, docs = true, project = true, publication = true, talk = true}
  [comments.disqus]
    shortname = ""  
    show_count = true 
  [comments.commento]
    url = ""

[search]
  engine = 0
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

[map]
  engine = 0
  api_key = ""
  zoom = 15

[marketing]
  google_analytics = ""
  google_tag_manager = ""
