# Run the cron jorb in docker
name: docker_cron

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # daily



jobs:
  build:
    runs-on: ubuntu-latest
    services:
      accessor:
        image: docker://dapperstats/accessor:latest
      salvage:
        image: docker://dapperstats/salvage:latest
    steps:
      - uses: actions/checkout@v3
      - name: get from accessor
        run: docker cp accesor:/data .