# Run the cron jorb in docker
name: docker_cron

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # daily



jobs:
  salvage_pipeline:
    name: salvage pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: |
          docker pull dapperstats/accessor
          docker pull dapperstats/salvage