# Run the cron jorb in docker
name: docker_cron

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # daily



jobs:
  build:
    runs-on: ubuntu-latest
    services:
      accessor:
        image: docker://dapperstats/accessor:latest
          - 3001:3000
    
      salvage:
        image: docker://dapperstats/salvage:latest
        ports:
          - 4001:4000

    steps:
      - uses: actions/checkout@v3