# Run the cron jorb in docker

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # daily

name: docker_cron

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://dapperstats/accessor:latest
    steps:
      - uses: actions/checkout@v3