# Run the cron jorb in docker
name: docker_cron

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # daily



jobs:
  salvage_pipeline:
    name: salvage pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install containers
        run: |
          docker pull dapperstats/accessor
          docker pull dapperstats/salvage
      - name: start and name containers
        run: |
          docker run --name acc --restart=always -i dapperstats/accessor