# build and publish the docker image when the version is tagged under semantic versioning
# the cron job release tags are formatted using date-time stamp, not semantic version, allowing for differentiation
# based on https://github.com/docker/build-push-action

name: docker_image_publish

on:
  push:
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}


jobs:
  build_docker_image:
    name: build docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into ${{ env.REGISTRY }} except on PR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: dapperstats/salvage
          tag-custom: latest
          tag-semver: |
            {{raw}}   

      - name: Build and push Docker image except on PR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }} 
#           tags: dapperstats/salvage:latest
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/Dockerfile
