# Run the cron job in docker container
name: cron_experiment

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # daily



jobs:
  salvage_pipeline:
    name: experimenting 
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install containers
        run: |
          docker pull dapperstats/accessor
          docker pull dapperstats/salvage
      - name: start and name containers
        run: |
          docker run --name acc --restart=always -i dapperstats/accessor -e "r=https://filelib.wildlife.ca.gov/Public/salvage/Salvage_data_FTP.accdb"


          